### ISSUE TITLE
Installation - error

### ISSUE THREAD

**Issue by enot14134** [Imbrosci/synaptic-vesicles-detection#5]
Hi, 

I am enthusiastic to use your program for the automated segmentation and counting of synaptic vesicles however I am very inexperienced with python.

I am attempting to install your program on a Mac with Anaconda running Python version 3.9.
When I to install required libraries using requirements.txt I receive an error when it gets to opencv-python-headless==4.3.0.38.

I would appreciate any guidance. I have tried using pip3 for the installation and upgrading pip but it has not solved the issue.

Part of error code below:
Elenis-MacBook-Pro:synaptic-vesicles-detection-master eleninotaras$ pip install -r requirements.txt
Collecting matplotlib==3.4.3
  Using cached matplotlib-3.4.3-cp39-cp39-macosx_10_9_x86_64.whl (7.2 MB)
Collecting numpy==1.21.3
  Using cached numpy-1.21.3-cp39-cp39-macosx_10_9_x86_64.whl (17.0 MB)
Collecting pandas==1.3.4
  Using cached pandas-1.3.4-cp39-cp39-macosx_10_9_x86_64.whl (11.6 MB)
Collecting Pillow==8.4.0
  Using cached Pillow-8.4.0-cp39-cp39-macosx_10_10_x86_64.whl (3.0 MB)
Collecting scikit_learn==1.0.1
  Using cached scikit_learn-1.0.1-cp39-cp39-macosx_10_13_x86_64.whl (8.0 MB)
Collecting scipy==1.7.1
  Using cached scipy-1.7.1-cp39-cp39-macosx_10_9_x86_64.whl (32.8 MB)
Collecting seaborn==0.11.2
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting XlsxWriter==3.0.1
  Using cached XlsxWriter-3.0.1-py3-none-any.whl (148 kB)
Collecting opencv-python-headless==4.3.0.38
  Using cached opencv-python-headless-4.3.0.38.tar.gz (88.0 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [339 lines of output]
      Ignoring numpy: markers 'python_version == "3.5"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7"' don't match your environment

**Comment by Imbrosci** [comment]
Hi,

thank you for the interest.
You could try first to remove  the version of opencv-python-headless by removing '==4.3.0.38' from the requirements.txt file, or remove the line opencv-python-headless==4.3.0.38 in the requirements.txt file, entirely, and install opencv separately.
I need to warn you that I am not sure that the tool will work on a Mac (this is another issue that you may have even after a successful installation). There is a bug (at least in a couple of Mac versions we tested on) that prevent the Graphical User Interface that the tool used to work properly. You can give it a try and let me know!
Good luck,
Barbara
