### ISSUE TITLE
Starting Analysis

### ISSUE THREAD

**Issue by Tmoore9393** [Imbrosci/synaptic-vesicles-detection#6]
Hello,

I hope you can help with an error I am receiving while trying to test this script. I have TEM image that I have placed in the appropriate folder, and I started the analysis
Name "test"
Enter the pixel size (1 slide!) in nanometer "3500"
Do you want the estimation of the vesicle area? (y/n) " y"

On the command menu, the following error occurs ----
ValueError: image has wrong mode
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\14039\anaconda3\envs\env_TEM\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\14039\Documents\GitHub\synaptic-vesicles-detection\Gui_vesicle_detection.py", line 184, in start_analysis2
    self.sliding_detection()
  File "C:\Users\14039\Documents\GitHub\synaptic-vesicles-detection\Gui_vesicle_detection.py", line 562, in sliding_detection
    img = self.img_to_analyse.resize((
  File "C:\Users\14039\anaconda3\envs\env_TEM\lib\site-packages\PIL\Image.py", line 2008, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: image has wrong mode
----------------------------------------------

If you have some suggestions to fix this or how to input the analysis information properly, I would gladly appreciate this!

Thanks

PS. I wonder if this is to do with the pixel size to nm conversion or how I measure this. If you have an example, maybe this will solve my confusion.

**Comment by Imbrosci** [comment]
Hi,
it has likely something to do with the pixel size information. You should enter the size of 1 pixel, it should be something around 10, 5 or 2 nm (or even smaller if you have high resolution images). If you have images with pixels of a much larger size it is hard to see synaptic vesicles, anyway (from my experience). You have entered 3500 nm, I guess you meant this is the size of 1 axis of the entire image, is it so? How many pixels do your images have? If you know this, you can easily calculate the size of a single pixel. Let's say you have a 1024x1024 pixels image with 3500x3500 nm of imaged tissue, in this case the size of one pixel would be circa 3.42x3.42 nm (3500/1024). Remember to use images with the same resolution if you want to analyse many images at once.
I hope this helps you! 
Let me know!
Barbara
